@startuml
namespace main {
    class Edge << (S,Aquamarine) >> {
        - u int
        - weight float64

    }
    class Graph << (S,Aquamarine) >> {
        - edges []Edge
        - adjList <font color=blue>map</font>[int][]Edge
        - vertexCount int

        + AddEdge(u int, v int, weight float64) 
        + MaxFlow(source int, sink int) float64

    }
}


@enduml
