@startuml
namespace main {
    class Edge << (S,Aquamarine) >> {
        - u: int
        - weight: float64

    }
    class Graph << (S,Aquamarine) >> {
        - edges: []Edge
        - adjList: <font color=blue>map</font>[int][]Edge
        - vertexCount: int

        + AddEdge(в u int,в v int,в weight float64)
        + MaxFlow(в source int,в sink int): вых float64

    }
}

@enduml
