@startuml
namespace main {
    class BasicCustomer << (S,Aquamarine) >> {
        - name string
        - balance int
        - tickets <font color=blue>map</font>[Movie]Tickets

        - printTicketsOfCurrentHall(hallNumber int) 
        - buyTicket(hallI HallI, movie Movie, countOfTickets int) error

    }
    class Beneficiary << (S,Aquamarine) >> {
        - name string
        - balance int
        - tickets <font color=blue>map</font>[Movie]Tickets

        - printTicketsOfCurrentHall(hallNumber int) 
        - buyTicket(hallI HallI, movie Movie, countOfTickets int) error

    }
    class Cinema << (S,Aquamarine) >> {
        - adress string
        - halls []*Hall
        - vipHalls []*VipHall

    }
    interface CustomerI  {
        - printTicketsOfCurrentHall(hallNumber int) 
        - buyTicket(hall HallI, movie Movie, countOfTickets int) error

    }
    class Hall << (S,Aquamarine) >> {
        - number int
        - movieMap <font color=blue>map</font>[Movie]int
        - capacity int

        - getAddedCostCoefficient() int
        - getCurrentHall() (*Hall, int, int, bool)

    }
    interface HallI  {
        - getCurrentHall() (*Hall, int, int, bool)
        - getAddedCostCoefficient() int

    }
    class Movie << (S,Aquamarine) >> {
        - title string
        - startTime time.Time
        - duration time.Duration
        - ticketPrice int

    }
    class Tickets << (S,Aquamarine) >> {
        - isVipHall bool
        - hallNumber int
        - movie Movie
        - price int
        - countOfTickets int

    }
    class VipHall << (S,Aquamarine) >> {
        - addedCostCoefficient int

        - getAddedCostCoefficient() int
        - getCurrentHall() (*Hall, int, int, bool)

    }
}
"main.CustomerI" *-- "main.BasicCustomer"
"main.CustomerI" *-- "main.Beneficiary"
"main.HallI" *-- "main.Hall"
"main.Hall" *-- "main.VipHall"
"main.HallI" *-- "main.VipHall"

"main.CustomerI" <|-- "main.BasicCustomer"
"main.CustomerI" <|-- "main.Beneficiary"
"main.HallI" <|-- "main.Hall"
"main.HallI" <|-- "main.VipHall"

@enduml
